# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.co2_value import CO2Value  # noqa: F401,E501
from swagger_server import util


class InlineResponse2004(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, room_name: str=None, co2_data: List[CO2Value]=None):  # noqa: E501
        """InlineResponse2004 - a model defined in Swagger

        :param room_name: The room_name of this InlineResponse2004.  # noqa: E501
        :type room_name: str
        :param co2_data: The co2_data of this InlineResponse2004.  # noqa: E501
        :type co2_data: List[CO2Value]
        """
        self.swagger_types = {
            'room_name': str,
            'co2_data': List[CO2Value]
        }

        self.attribute_map = {
            'room_name': 'room_name',
            'co2_data': 'co2_data'
        }
        self._room_name = room_name
        self._co2_data = co2_data

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2004':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_4 of this InlineResponse2004.  # noqa: E501
        :rtype: InlineResponse2004
        """
        return util.deserialize_model(dikt, cls)

    @property
    def room_name(self) -> str:
        """Gets the room_name of this InlineResponse2004.

        Name of the room  # noqa: E501

        :return: The room_name of this InlineResponse2004.
        :rtype: str
        """
        return self._room_name

    @room_name.setter
    def room_name(self, room_name: str):
        """Sets the room_name of this InlineResponse2004.

        Name of the room  # noqa: E501

        :param room_name: The room_name of this InlineResponse2004.
        :type room_name: str
        """

        self._room_name = room_name

    @property
    def co2_data(self) -> List[CO2Value]:
        """Gets the co2_data of this InlineResponse2004.

        List of CO2 level values for the room  # noqa: E501

        :return: The co2_data of this InlineResponse2004.
        :rtype: List[CO2Value]
        """
        return self._co2_data

    @co2_data.setter
    def co2_data(self, co2_data: List[CO2Value]):
        """Sets the co2_data of this InlineResponse2004.

        List of CO2 level values for the room  # noqa: E501

        :param co2_data: The co2_data of this InlineResponse2004.
        :type co2_data: List[CO2Value]
        """

        self._co2_data = co2_data
