# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.light_intensity_value import LightIntensityValue  # noqa: F401,E501
from swagger_server import util


class LightIntensityRoom(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, light_intensity_values: List[LightIntensityValue]=None):  # noqa: E501
        """LightIntensityRoom - a model defined in Swagger

        :param name: The name of this LightIntensityRoom.  # noqa: E501
        :type name: str
        :param light_intensity_values: The light_intensity_values of this LightIntensityRoom.  # noqa: E501
        :type light_intensity_values: List[LightIntensityValue]
        """
        self.swagger_types = {
            'name': str,
            'light_intensity_values': List[LightIntensityValue]
        }

        self.attribute_map = {
            'name': 'name',
            'light_intensity_values': 'light_intensity_values'
        }
        self._name = name
        self._light_intensity_values = light_intensity_values

    @classmethod
    def from_dict(cls, dikt) -> 'LightIntensityRoom':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LightIntensityRoom of this LightIntensityRoom.  # noqa: E501
        :rtype: LightIntensityRoom
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this LightIntensityRoom.

        Name of the room  # noqa: E501

        :return: The name of this LightIntensityRoom.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this LightIntensityRoom.

        Name of the room  # noqa: E501

        :param name: The name of this LightIntensityRoom.
        :type name: str
        """

        self._name = name

    @property
    def light_intensity_values(self) -> List[LightIntensityValue]:
        """Gets the light_intensity_values of this LightIntensityRoom.

        Light intensity readings for a specific room  # noqa: E501

        :return: The light_intensity_values of this LightIntensityRoom.
        :rtype: List[LightIntensityValue]
        """
        return self._light_intensity_values

    @light_intensity_values.setter
    def light_intensity_values(self, light_intensity_values: List[LightIntensityValue]):
        """Sets the light_intensity_values of this LightIntensityRoom.

        Light intensity readings for a specific room  # noqa: E501

        :param light_intensity_values: The light_intensity_values of this LightIntensityRoom.
        :type light_intensity_values: List[LightIntensityValue]
        """

        self._light_intensity_values = light_intensity_values
