# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.co2_value import CO2Value  # noqa: F401,E501
from swagger_server import util


class CO2Room(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, co2_values: List[CO2Value]=None):  # noqa: E501
        """CO2Room - a model defined in Swagger

        :param name: The name of this CO2Room.  # noqa: E501
        :type name: str
        :param co2_values: The co2_values of this CO2Room.  # noqa: E501
        :type co2_values: List[CO2Value]
        """
        self.swagger_types = {
            'name': str,
            'co2_values': List[CO2Value]
        }

        self.attribute_map = {
            'name': 'name',
            'co2_values': 'co2_values'
        }
        self._name = name
        self._co2_values = co2_values

    @classmethod
    def from_dict(cls, dikt) -> 'CO2Room':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CO2Room of this CO2Room.  # noqa: E501
        :rtype: CO2Room
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this CO2Room.

        Name of the room  # noqa: E501

        :return: The name of this CO2Room.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this CO2Room.

        Name of the room  # noqa: E501

        :param name: The name of this CO2Room.
        :type name: str
        """

        self._name = name

    @property
    def co2_values(self) -> List[CO2Value]:
        """Gets the co2_values of this CO2Room.

        CO2 level readings for a specific room  # noqa: E501

        :return: The co2_values of this CO2Room.
        :rtype: List[CO2Value]
        """
        return self._co2_values

    @co2_values.setter
    def co2_values(self, co2_values: List[CO2Value]):
        """Sets the co2_values of this CO2Room.

        CO2 level readings for a specific room  # noqa: E501

        :param co2_values: The co2_values of this CO2Room.
        :type co2_values: List[CO2Value]
        """

        self._co2_values = co2_values
