# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.facility_rooms_rooms import FacilityRoomsRooms  # noqa: F401,E501
from swagger_server import util


class FacilityRooms(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, rooms: List[FacilityRoomsRooms] = None):  # noqa: E501
        """FacilityRooms - a model defined in Swagger

        :param rooms: The rooms of this FacilityRooms.  # noqa: E501
        :type rooms: List[FacilityRoomsRooms]
        """
        self.swagger_types = {"rooms": List[FacilityRoomsRooms]}

        self.attribute_map = {"rooms": "rooms"}
        self._rooms = rooms

    @classmethod
    def from_dict(cls, dikt) -> "FacilityRooms":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FacilityRooms of this FacilityRooms.  # noqa: E501
        :rtype: FacilityRooms
        """
        return util.deserialize_model(dikt, cls)

    @property
    def rooms(self) -> List[FacilityRoomsRooms]:
        """Gets the rooms of this FacilityRooms.

        List of rooms with their facilities  # noqa: E501

        :return: The rooms of this FacilityRooms.
        :rtype: List[FacilityRoomsRooms]
        """
        return self._rooms

    @rooms.setter
    def rooms(self, rooms: List[FacilityRoomsRooms]):
        """Sets the rooms of this FacilityRooms.

        List of rooms with their facilities  # noqa: E501

        :param rooms: The rooms of this FacilityRooms.
        :type rooms: List[FacilityRoomsRooms]
        """

        self._rooms = rooms
