# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.room_facilities import RoomFacilities  # noqa: F401,E501
from swagger_server import util


class FacilityRoomsRooms(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str = None, facilities: RoomFacilities = None):  # noqa: E501
        """FacilityRoomsRooms - a model defined in Swagger

        :param name: The name of this FacilityRoomsRooms.  # noqa: E501
        :type name: str
        :param facilities: The facilities of this FacilityRoomsRooms.  # noqa: E501
        :type facilities: RoomFacilities
        """
        self.swagger_types = {"name": str, "facilities": RoomFacilities}

        self.attribute_map = {"name": "name", "facilities": "facilities"}
        self._name = name
        self._facilities = facilities

    @classmethod
    def from_dict(cls, dikt) -> "FacilityRoomsRooms":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FacilityRooms_rooms of this FacilityRoomsRooms.  # noqa: E501
        :rtype: FacilityRoomsRooms
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this FacilityRoomsRooms.

        Name of the room  # noqa: E501

        :return: The name of this FacilityRoomsRooms.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this FacilityRoomsRooms.

        Name of the room  # noqa: E501

        :param name: The name of this FacilityRoomsRooms.
        :type name: str
        """

        self._name = name

    @property
    def facilities(self) -> RoomFacilities:
        """Gets the facilities of this FacilityRoomsRooms.


        :return: The facilities of this FacilityRoomsRooms.
        :rtype: RoomFacilities
        """
        return self._facilities

    @facilities.setter
    def facilities(self, facilities: RoomFacilities):
        """Sets the facilities of this FacilityRoomsRooms.


        :param facilities: The facilities of this FacilityRoomsRooms.
        :type facilities: RoomFacilities
        """

        self._facilities = facilities
