# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class HumidityValue(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, timestamp: datetime=None, humidity: float=None):  # noqa: E501
        """HumidityValue - a model defined in Swagger

        :param timestamp: The timestamp of this HumidityValue.  # noqa: E501
        :type timestamp: datetime
        :param humidity: The humidity of this HumidityValue.  # noqa: E501
        :type humidity: float
        """
        self.swagger_types = {
            'timestamp': datetime,
            'humidity': float
        }

        self.attribute_map = {
            'timestamp': 'timestamp',
            'humidity': 'humidity'
        }
        self._timestamp = timestamp
        self._humidity = humidity

    @classmethod
    def from_dict(cls, dikt) -> 'HumidityValue':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HumidityValue of this HumidityValue.  # noqa: E501
        :rtype: HumidityValue
        """
        return util.deserialize_model(dikt, cls)

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this HumidityValue.

        Timestamp of the humidity reading  # noqa: E501

        :return: The timestamp of this HumidityValue.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this HumidityValue.

        Timestamp of the humidity reading  # noqa: E501

        :param timestamp: The timestamp of this HumidityValue.
        :type timestamp: datetime
        """

        self._timestamp = timestamp

    @property
    def humidity(self) -> float:
        """Gets the humidity of this HumidityValue.

        Humidity level in percentage  # noqa: E501

        :return: The humidity of this HumidityValue.
        :rtype: float
        """
        return self._humidity

    @humidity.setter
    def humidity(self, humidity: float):
        """Sets the humidity of this HumidityValue.

        Humidity level in percentage  # noqa: E501

        :param humidity: The humidity of this HumidityValue.
        :type humidity: float
        """

        self._humidity = humidity
