# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response201_room import InlineResponse201Room  # noqa: F401,E501
from swagger_server import util


class InlineResponse201(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, room: InlineResponse201Room=None):  # noqa: E501
        """InlineResponse201 - a model defined in Swagger

        :param room: The room of this InlineResponse201.  # noqa: E501
        :type room: InlineResponse201Room
        """
        self.swagger_types = {
            'room': InlineResponse201Room
        }

        self.attribute_map = {
            'room': 'room'
        }
        self._room = room

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse201':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_201 of this InlineResponse201.  # noqa: E501
        :rtype: InlineResponse201
        """
        return util.deserialize_model(dikt, cls)

    @property
    def room(self) -> InlineResponse201Room:
        """Gets the room of this InlineResponse201.


        :return: The room of this InlineResponse201.
        :rtype: InlineResponse201Room
        """
        return self._room

    @room.setter
    def room(self, room: InlineResponse201Room):
        """Sets the room of this InlineResponse201.


        :param room: The room of this InlineResponse201.
        :type room: InlineResponse201Room
        """

        self._room = room
