# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LightIntensityValue(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, timestamp: datetime = None, light_intensity: float = None):  # noqa: E501
        """LightIntensityValue - a model defined in Swagger

        :param timestamp: The timestamp of this LightIntensityValue.  # noqa: E501
        :type timestamp: datetime
        :param light_intensity: The light_intensity of this LightIntensityValue.  # noqa: E501
        :type light_intensity: float
        """
        self.swagger_types = {"timestamp": datetime, "light_intensity": float}

        self.attribute_map = {
            "timestamp": "timestamp",
            "light_intensity": "light_intensity",
        }
        self._timestamp = timestamp
        self._light_intensity = light_intensity

    @classmethod
    def from_dict(cls, dikt) -> "LightIntensityValue":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LightIntensityValue of this LightIntensityValue.  # noqa: E501
        :rtype: LightIntensityValue
        """
        return util.deserialize_model(dikt, cls)

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this LightIntensityValue.

        Timestamp of the light intensity reading  # noqa: E501

        :return: The timestamp of this LightIntensityValue.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this LightIntensityValue.

        Timestamp of the light intensity reading  # noqa: E501

        :param timestamp: The timestamp of this LightIntensityValue.
        :type timestamp: datetime
        """

        self._timestamp = timestamp

    @property
    def light_intensity(self) -> float:
        """Gets the light_intensity of this LightIntensityValue.

        Light intensity in a room  # noqa: E501

        :return: The light_intensity of this LightIntensityValue.
        :rtype: float
        """
        return self._light_intensity

    @light_intensity.setter
    def light_intensity(self, light_intensity: float):
        """Sets the light_intensity of this LightIntensityValue.

        Light intensity in a room  # noqa: E501

        :param light_intensity: The light_intensity of this LightIntensityValue.
        :type light_intensity: float
        """

        self._light_intensity = light_intensity
