# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.voc_value import VOCValue  # noqa: F401,E501
from swagger_server import util


class VOCRoom(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str = None, voc_values: List[VOCValue] = None):  # noqa: E501
        """VOCRoom - a model defined in Swagger

        :param name: The name of this VOCRoom.  # noqa: E501
        :type name: str
        :param voc_values: The voc_values of this VOCRoom.  # noqa: E501
        :type voc_values: List[VOCValue]
        """
        self.swagger_types = {"name": str, "voc_values": List[VOCValue]}

        self.attribute_map = {"name": "name", "voc_values": "voc_values"}
        self._name = name
        self._voc_values = voc_values

    @classmethod
    def from_dict(cls, dikt) -> "VOCRoom":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VOCRoom of this VOCRoom.  # noqa: E501
        :rtype: VOCRoom
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this VOCRoom.

        Name of the room  # noqa: E501

        :return: The name of this VOCRoom.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this VOCRoom.

        Name of the room  # noqa: E501

        :param name: The name of this VOCRoom.
        :type name: str
        """

        self._name = name

    @property
    def voc_values(self) -> List[VOCValue]:
        """Gets the voc_values of this VOCRoom.

        VOC level readings for a specific room  # noqa: E501

        :return: The voc_values of this VOCRoom.
        :rtype: List[VOCValue]
        """
        return self._voc_values

    @voc_values.setter
    def voc_values(self, voc_values: List[VOCValue]):
        """Sets the voc_values of this VOCRoom.

        VOC level readings for a specific room  # noqa: E501

        :param voc_values: The voc_values of this VOCRoom.
        :type voc_values: List[VOCValue]
        """

        self._voc_values = voc_values
