# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SoundValue(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, timestamp: datetime=None, sound_level: float=None):  # noqa: E501
        """SoundValue - a model defined in Swagger

        :param timestamp: The timestamp of this SoundValue.  # noqa: E501
        :type timestamp: datetime
        :param sound_level: The sound_level of this SoundValue.  # noqa: E501
        :type sound_level: float
        """
        self.swagger_types = {
            'timestamp': datetime,
            'sound_level': float
        }

        self.attribute_map = {
            'timestamp': 'timestamp',
            'sound_level': 'sound_level'
        }
        self._timestamp = timestamp
        self._sound_level = sound_level

    @classmethod
    def from_dict(cls, dikt) -> 'SoundValue':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SoundValue of this SoundValue.  # noqa: E501
        :rtype: SoundValue
        """
        return util.deserialize_model(dikt, cls)

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this SoundValue.

        Timestamp of the sound level reading  # noqa: E501

        :return: The timestamp of this SoundValue.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this SoundValue.

        Timestamp of the sound level reading  # noqa: E501

        :param timestamp: The timestamp of this SoundValue.
        :type timestamp: datetime
        """

        self._timestamp = timestamp

    @property
    def sound_level(self) -> float:
        """Gets the sound_level of this SoundValue.

        Sound level in decibels (dB)  # noqa: E501

        :return: The sound_level of this SoundValue.
        :rtype: float
        """
        return self._sound_level

    @sound_level.setter
    def sound_level(self, sound_level: float):
        """Sets the sound_level of this SoundValue.

        Sound level in decibels (dB)  # noqa: E501

        :param sound_level: The sound_level of this SoundValue.
        :type sound_level: float
        """

        self._sound_level = sound_level
