# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from swagger_server import util
from swagger_server.models.air_quality_value import AirQualityValue  # noqa: F401,E501
from swagger_server.models.base_model_ import Model


class AirQualityRoom(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(
        self, name: str = None, air_quality_data: List[AirQualityValue] = None
    ):  # noqa: E501
        """AirQualityRoom - a model defined in Swagger

        :param name: The name of this AirQualityRoom.  # noqa: E501
        :type name: str
        :param air_quality_data: The air_quality_data of this AirQualityRoom.  # noqa: E501
        :type air_quality_data: List[AirQualityValue]
        """
        self.swagger_types = {"name": str, "air_quality_data": List[AirQualityValue]}

        self.attribute_map = {"name": "name", "air_quality_data": "air_quality_data"}
        self._name = name
        self._air_quality_data = air_quality_data

    @classmethod
    def from_dict(cls, dikt) -> "AirQualityRoom":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AirQualityRoom of this AirQualityRoom.  # noqa: E501
        :rtype: AirQualityRoom
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this AirQualityRoom.

        Name of the room  # noqa: E501

        :return: The name of this AirQualityRoom.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this AirQualityRoom.

        Name of the room  # noqa: E501

        :param name: The name of this AirQualityRoom.
        :type name: str
        """

        self._name = name

    @property
    def air_quality_data(self) -> List[AirQualityValue]:
        """Gets the air_quality_data of this AirQualityRoom.

        Air quality data for a specific room  # noqa: E501

        :return: The air_quality_data of this AirQualityRoom.
        :rtype: List[AirQualityValue]
        """
        return self._air_quality_data

    @air_quality_data.setter
    def air_quality_data(self, air_quality_data: List[AirQualityValue]):
        """Sets the air_quality_data of this AirQualityRoom.

        Air quality data for a specific room  # noqa: E501

        :param air_quality_data: The air_quality_data of this AirQualityRoom.
        :type air_quality_data: List[AirQualityValue]
        """

        self._air_quality_data = air_quality_data
