# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from swagger_server import util
from swagger_server.models.base_model_ import Model


class CO2Value(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, timestamp: datetime = None, co2_level: float = None):  # noqa: E501
        """CO2Value - a model defined in Swagger

        :param timestamp: The timestamp of this CO2Value.  # noqa: E501
        :type timestamp: datetime
        :param co2_level: The co2_level of this CO2Value.  # noqa: E501
        :type co2_level: float
        """
        self.swagger_types = {"timestamp": datetime, "co2_level": float}

        self.attribute_map = {"timestamp": "timestamp", "co2_level": "co2_level"}
        self._timestamp = timestamp
        self._co2_level = co2_level

    @classmethod
    def from_dict(cls, dikt) -> "CO2Value":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CO2Value of this CO2Value.  # noqa: E501
        :rtype: CO2Value
        """
        return util.deserialize_model(dikt, cls)

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this CO2Value.

        Timestamp of the CO2 level reading  # noqa: E501

        :return: The timestamp of this CO2Value.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this CO2Value.

        Timestamp of the CO2 level reading  # noqa: E501

        :param timestamp: The timestamp of this CO2Value.
        :type timestamp: datetime
        """

        self._timestamp = timestamp

    @property
    def co2_level(self) -> float:
        """Gets the co2_level of this CO2Value.

        Concentration of CO2 level in the room  # noqa: E501

        :return: The co2_level of this CO2Value.
        :rtype: float
        """
        return self._co2_level

    @co2_level.setter
    def co2_level(self, co2_level: float):
        """Sets the co2_level of this CO2Value.

        Concentration of CO2 level in the room  # noqa: E501

        :param co2_level: The co2_level of this CO2Value.
        :type co2_level: float
        """

        self._co2_level = co2_level
