# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from swagger_server import util
from swagger_server.models.base_model_ import Model
from swagger_server.models.humidity_value import HumidityValue  # noqa: F401,E501


class HumidityRoom(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str = None, humidity_values: List[HumidityValue] = None):  # noqa: E501
        """HumidityRoom - a model defined in Swagger

        :param name: The name of this HumidityRoom.  # noqa: E501
        :type name: str
        :param humidity_values: The humidity_values of this HumidityRoom.  # noqa: E501
        :type humidity_values: List[HumidityValue]
        """
        self.swagger_types = {"name": str, "humidity_values": List[HumidityValue]}

        self.attribute_map = {"name": "name", "humidity_values": "humidity_values"}
        self._name = name
        self._humidity_values = humidity_values

    @classmethod
    def from_dict(cls, dikt) -> "HumidityRoom":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HumidityRoom of this HumidityRoom.  # noqa: E501
        :rtype: HumidityRoom
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this HumidityRoom.

        Name of the room  # noqa: E501

        :return: The name of this HumidityRoom.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this HumidityRoom.

        Name of the room  # noqa: E501

        :param name: The name of this HumidityRoom.
        :type name: str
        """

        self._name = name

    @property
    def humidity_values(self) -> List[HumidityValue]:
        """Gets the humidity_values of this HumidityRoom.

        Humidity readings for a specific room  # noqa: E501

        :return: The humidity_values of this HumidityRoom.
        :rtype: List[HumidityValue]
        """
        return self._humidity_values

    @humidity_values.setter
    def humidity_values(self, humidity_values: List[HumidityValue]):
        """Sets the humidity_values of this HumidityRoom.

        Humidity readings for a specific room  # noqa: E501

        :param humidity_values: The humidity_values of this HumidityRoom.
        :type humidity_values: List[HumidityValue]
        """

        self._humidity_values = humidity_values
