# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from swagger_server import util
from swagger_server.models.base_model_ import Model
<<<<<<< HEAD:src/application/src/api/swagger_server/models/inline_response2003.py
from swagger_server.models.co2_value import CO2Value  # noqa: F401,E501
=======
from swagger_server.models.air_quality_value import AirQualityValue  # noqa: F401,E501
from swagger_server import util
>>>>>>> API_Database:src/application/src/swagger_server/models/inline_response2003.py


class InlineResponse2003(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
<<<<<<< HEAD:src/application/src/api/swagger_server/models/inline_response2003.py

    def __init__(self, room_name: str = None, co2_data: List[CO2Value] = None):  # noqa: E501
=======
    def __init__(self, room_name: str=None, air_quality_data: List[AirQualityValue]=None):  # noqa: E501
>>>>>>> API_Database:src/application/src/swagger_server/models/inline_response2003.py
        """InlineResponse2003 - a model defined in Swagger

        :param room_name: The room_name of this InlineResponse2003.  # noqa: E501
        :type room_name: str
        :param air_quality_data: The air_quality_data of this InlineResponse2003.  # noqa: E501
        :type air_quality_data: List[AirQualityValue]
        """
<<<<<<< HEAD:src/application/src/api/swagger_server/models/inline_response2003.py
        self.swagger_types = {"room_name": str, "co2_data": List[CO2Value]}

        self.attribute_map = {"room_name": "room_name", "co2_data": "co2_data"}
=======
        self.swagger_types = {
            'room_name': str,
            'air_quality_data': List[AirQualityValue]
        }

        self.attribute_map = {
            'room_name': 'room_name',
            'air_quality_data': 'air_quality_data'
        }
>>>>>>> API_Database:src/application/src/swagger_server/models/inline_response2003.py
        self._room_name = room_name
        self._air_quality_data = air_quality_data

    @classmethod
    def from_dict(cls, dikt) -> "InlineResponse2003":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_3 of this InlineResponse2003.  # noqa: E501
        :rtype: InlineResponse2003
        """
        return util.deserialize_model(dikt, cls)

    @property
    def room_name(self) -> str:
        """Gets the room_name of this InlineResponse2003.

        Name of the room  # noqa: E501

        :return: The room_name of this InlineResponse2003.
        :rtype: str
        """
        return self._room_name

    @room_name.setter
    def room_name(self, room_name: str):
        """Sets the room_name of this InlineResponse2003.

        Name of the room  # noqa: E501

        :param room_name: The room_name of this InlineResponse2003.
        :type room_name: str
        """

        self._room_name = room_name

    @property
    def air_quality_data(self) -> List[AirQualityValue]:
        """Gets the air_quality_data of this InlineResponse2003.

        List of air quality values for the room  # noqa: E501

        :return: The air_quality_data of this InlineResponse2003.
        :rtype: List[AirQualityValue]
        """
        return self._air_quality_data

    @air_quality_data.setter
    def air_quality_data(self, air_quality_data: List[AirQualityValue]):
        """Sets the air_quality_data of this InlineResponse2003.

        List of air quality values for the room  # noqa: E501

        :param air_quality_data: The air_quality_data of this InlineResponse2003.
        :type air_quality_data: List[AirQualityValue]
        """

        self._air_quality_data = air_quality_data
