# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from swagger_server import util
from swagger_server.models.base_model_ import Model
<<<<<<< HEAD:src/application/src/api/swagger_server/models/inline_response2006.py
from swagger_server.models.sound_value import SoundValue  # noqa: F401,E501
=======
from swagger_server.models.light_intensity_value import LightIntensityValue  # noqa: F401,E501
from swagger_server import util
>>>>>>> API_Database:src/application/src/swagger_server/models/inline_response2006.py


class InlineResponse2006(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
<<<<<<< HEAD:src/application/src/api/swagger_server/models/inline_response2006.py

    def __init__(self, room_name: str = None, sound_data: List[SoundValue] = None):  # noqa: E501
=======
    def __init__(self, room_name: str=None, light_intensity_data: List[LightIntensityValue]=None):  # noqa: E501
>>>>>>> API_Database:src/application/src/swagger_server/models/inline_response2006.py
        """InlineResponse2006 - a model defined in Swagger

        :param room_name: The room_name of this InlineResponse2006.  # noqa: E501
        :type room_name: str
        :param light_intensity_data: The light_intensity_data of this InlineResponse2006.  # noqa: E501
        :type light_intensity_data: List[LightIntensityValue]
        """
<<<<<<< HEAD:src/application/src/api/swagger_server/models/inline_response2006.py
        self.swagger_types = {"room_name": str, "sound_data": List[SoundValue]}

        self.attribute_map = {"room_name": "room_name", "sound_data": "sound_data"}
=======
        self.swagger_types = {
            'room_name': str,
            'light_intensity_data': List[LightIntensityValue]
        }

        self.attribute_map = {
            'room_name': 'room_name',
            'light_intensity_data': 'light_intensity_data'
        }
>>>>>>> API_Database:src/application/src/swagger_server/models/inline_response2006.py
        self._room_name = room_name
        self._light_intensity_data = light_intensity_data

    @classmethod
    def from_dict(cls, dikt) -> "InlineResponse2006":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_6 of this InlineResponse2006.  # noqa: E501
        :rtype: InlineResponse2006
        """
        return util.deserialize_model(dikt, cls)

    @property
    def room_name(self) -> str:
        """Gets the room_name of this InlineResponse2006.

        Name of the room  # noqa: E501

        :return: The room_name of this InlineResponse2006.
        :rtype: str
        """
        return self._room_name

    @room_name.setter
    def room_name(self, room_name: str):
        """Sets the room_name of this InlineResponse2006.

        Name of the room  # noqa: E501

        :param room_name: The room_name of this InlineResponse2006.
        :type room_name: str
        """

        self._room_name = room_name

    @property
    def light_intensity_data(self) -> List[LightIntensityValue]:
        """Gets the light_intensity_data of this InlineResponse2006.

        List of light intensity values for the room  # noqa: E501

        :return: The light_intensity_data of this InlineResponse2006.
        :rtype: List[LightIntensityValue]
        """
        return self._light_intensity_data

    @light_intensity_data.setter
    def light_intensity_data(self, light_intensity_data: List[LightIntensityValue]):
        """Sets the light_intensity_data of this InlineResponse2006.

        List of light intensity values for the room  # noqa: E501

        :param light_intensity_data: The light_intensity_data of this InlineResponse2006.
        :type light_intensity_data: List[LightIntensityValue]
        """

        self._light_intensity_data = light_intensity_data
