# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.air_quality_value import AirQualityValue  # noqa: F401,E501
from swagger_server.models.co2_value import CO2Value  # noqa: F401,E501
from swagger_server.models.humidity_value import HumidityValue  # noqa: F401,E501
from swagger_server.models.light_intensity_value import LightIntensityValue  # noqa: F401,E501
from swagger_server.models.room_facilities import RoomFacilities  # noqa: F401,E501
from swagger_server.models.sound_value import SoundValue  # noqa: F401,E501
from swagger_server.models.temperature_value import TemperatureValue  # noqa: F401,E501
from swagger_server.models.voc_value import VOCValue  # noqa: F401,E501
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, air_quality: AirQualityValue=None, co2: CO2Value=None, humidity: HumidityValue=None, light_intensity: LightIntensityValue=None, sound: SoundValue=None, temperature: TemperatureValue=None, voc: VOCValue=None, room_facilites: RoomFacilities=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param name: The name of this InlineResponse200.  # noqa: E501
        :type name: str
        :param air_quality: The air_quality of this InlineResponse200.  # noqa: E501
        :type air_quality: AirQualityValue
        :param co2: The co2 of this InlineResponse200.  # noqa: E501
        :type co2: CO2Value
        :param humidity: The humidity of this InlineResponse200.  # noqa: E501
        :type humidity: HumidityValue
        :param light_intensity: The light_intensity of this InlineResponse200.  # noqa: E501
        :type light_intensity: LightIntensityValue
        :param sound: The sound of this InlineResponse200.  # noqa: E501
        :type sound: SoundValue
        :param temperature: The temperature of this InlineResponse200.  # noqa: E501
        :type temperature: TemperatureValue
        :param voc: The voc of this InlineResponse200.  # noqa: E501
        :type voc: VOCValue
        :param room_facilites: The room_facilites of this InlineResponse200.  # noqa: E501
        :type room_facilites: RoomFacilities
        """
        self.swagger_types = {
            'name': str,
            'air_quality': AirQualityValue,
            'co2': CO2Value,
            'humidity': HumidityValue,
            'light_intensity': LightIntensityValue,
            'sound': SoundValue,
            'temperature': TemperatureValue,
            'voc': VOCValue,
            'room_facilites': RoomFacilities
        }

        self.attribute_map = {
            'name': 'name',
            'air_quality': 'Air_Quality',
            'co2': 'CO2',
            'humidity': 'Humidity',
            'light_intensity': 'Light_Intensity',
            'sound': 'Sound',
            'temperature': 'Temperature',
            'voc': 'VOC',
            'room_facilites': 'Room_facilites'
        }
        self._name = name
        self._air_quality = air_quality
        self._co2 = co2
        self._humidity = humidity
        self._light_intensity = light_intensity
        self._sound = sound
        self._temperature = temperature
        self._voc = voc
        self._room_facilites = room_facilites

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this InlineResponse200.

        Name of the room  # noqa: E501

        :return: The name of this InlineResponse200.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this InlineResponse200.

        Name of the room  # noqa: E501

        :param name: The name of this InlineResponse200.
        :type name: str
        """

        self._name = name

    @property
    def air_quality(self) -> AirQualityValue:
        """Gets the air_quality of this InlineResponse200.


        :return: The air_quality of this InlineResponse200.
        :rtype: AirQualityValue
        """
        return self._air_quality

    @air_quality.setter
    def air_quality(self, air_quality: AirQualityValue):
        """Sets the air_quality of this InlineResponse200.


        :param air_quality: The air_quality of this InlineResponse200.
        :type air_quality: AirQualityValue
        """

        self._air_quality = air_quality

    @property
    def co2(self) -> CO2Value:
        """Gets the co2 of this InlineResponse200.


        :return: The co2 of this InlineResponse200.
        :rtype: CO2Value
        """
        return self._co2

    @co2.setter
    def co2(self, co2: CO2Value):
        """Sets the co2 of this InlineResponse200.


        :param co2: The co2 of this InlineResponse200.
        :type co2: CO2Value
        """

        self._co2 = co2

    @property
    def humidity(self) -> HumidityValue:
        """Gets the humidity of this InlineResponse200.


        :return: The humidity of this InlineResponse200.
        :rtype: HumidityValue
        """
        return self._humidity

    @humidity.setter
    def humidity(self, humidity: HumidityValue):
        """Sets the humidity of this InlineResponse200.


        :param humidity: The humidity of this InlineResponse200.
        :type humidity: HumidityValue
        """

        self._humidity = humidity

    @property
    def light_intensity(self) -> LightIntensityValue:
        """Gets the light_intensity of this InlineResponse200.


        :return: The light_intensity of this InlineResponse200.
        :rtype: LightIntensityValue
        """
        return self._light_intensity

    @light_intensity.setter
    def light_intensity(self, light_intensity: LightIntensityValue):
        """Sets the light_intensity of this InlineResponse200.


        :param light_intensity: The light_intensity of this InlineResponse200.
        :type light_intensity: LightIntensityValue
        """

        self._light_intensity = light_intensity

    @property
    def sound(self) -> SoundValue:
        """Gets the sound of this InlineResponse200.


        :return: The sound of this InlineResponse200.
        :rtype: SoundValue
        """
        return self._sound

    @sound.setter
    def sound(self, sound: SoundValue):
        """Sets the sound of this InlineResponse200.


        :param sound: The sound of this InlineResponse200.
        :type sound: SoundValue
        """

        self._sound = sound

    @property
    def temperature(self) -> TemperatureValue:
        """Gets the temperature of this InlineResponse200.


        :return: The temperature of this InlineResponse200.
        :rtype: TemperatureValue
        """
        return self._temperature

    @temperature.setter
    def temperature(self, temperature: TemperatureValue):
        """Sets the temperature of this InlineResponse200.


        :param temperature: The temperature of this InlineResponse200.
        :type temperature: TemperatureValue
        """

        self._temperature = temperature

    @property
    def voc(self) -> VOCValue:
        """Gets the voc of this InlineResponse200.


        :return: The voc of this InlineResponse200.
        :rtype: VOCValue
        """
        return self._voc

    @voc.setter
    def voc(self, voc: VOCValue):
        """Sets the voc of this InlineResponse200.


        :param voc: The voc of this InlineResponse200.
        :type voc: VOCValue
        """

        self._voc = voc

    @property
    def room_facilites(self) -> RoomFacilities:
        """Gets the room_facilites of this InlineResponse200.


        :return: The room_facilites of this InlineResponse200.
        :rtype: RoomFacilities
        """
        return self._room_facilites

    @room_facilites.setter
    def room_facilites(self, room_facilites: RoomFacilities):
        """Sets the room_facilites of this InlineResponse200.


        :param room_facilites: The room_facilites of this InlineResponse200.
        :type room_facilites: RoomFacilities
        """

        self._room_facilites = room_facilites
