# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from swagger_server import util
from swagger_server.models.base_model_ import Model
from swagger_server.models.voc_value import VOCValue  # noqa: F401,E501


class InlineResponse2009(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, room_name: str = None, voc_data: List[VOCValue] = None):  # noqa: E501
        """InlineResponse2009 - a model defined in Swagger

        :param room_name: The room_name of this InlineResponse2009.  # noqa: E501
        :type room_name: str
        :param voc_data: The voc_data of this InlineResponse2009.  # noqa: E501
        :type voc_data: List[VOCValue]
        """
        self.swagger_types = {"room_name": str, "voc_data": List[VOCValue]}

        self.attribute_map = {"room_name": "room_name", "voc_data": "voc_data"}
        self._room_name = room_name
        self._voc_data = voc_data

    @classmethod
    def from_dict(cls, dikt) -> "InlineResponse2009":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_9 of this InlineResponse2009.  # noqa: E501
        :rtype: InlineResponse2009
        """
        return util.deserialize_model(dikt, cls)

    @property
    def room_name(self) -> str:
        """Gets the room_name of this InlineResponse2009.

        Name of the room  # noqa: E501

        :return: The room_name of this InlineResponse2009.
        :rtype: str
        """
        return self._room_name

    @room_name.setter
    def room_name(self, room_name: str):
        """Sets the room_name of this InlineResponse2009.

        Name of the room  # noqa: E501

        :param room_name: The room_name of this InlineResponse2009.
        :type room_name: str
        """

        self._room_name = room_name

    @property
    def voc_data(self) -> List[VOCValue]:
        """Gets the voc_data of this InlineResponse2009.

        List of VOC values for the room  # noqa: E501

        :return: The voc_data of this InlineResponse2009.
        :rtype: List[VOCValue]
        """
        return self._voc_data

    @voc_data.setter
    def voc_data(self, voc_data: List[VOCValue]):
        """Sets the voc_data of this InlineResponse2009.

        List of VOC values for the room  # noqa: E501

        :param voc_data: The voc_data of this InlineResponse2009.
        :type voc_data: List[VOCValue]
        """

        self._voc_data = voc_data
