# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.air_quality_value import AirQualityValue  # noqa: F401,E501
from swagger_server.models.co2_value import CO2Value  # noqa: F401,E501
from swagger_server.models.humidity_value import HumidityValue  # noqa: F401,E501
from swagger_server.models.light_intensity_value import LightIntensityValue  # noqa: F401,E501
from swagger_server.models.room_facilities import RoomFacilities  # noqa: F401,E501
from swagger_server.models.sound_value import SoundValue  # noqa: F401,E501
from swagger_server.models.temperature_value import TemperatureValue  # noqa: F401,E501
from swagger_server.models.voc_value import VOCValue  # noqa: F401,E501
from swagger_server import util


class InlineResponse201Room(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, air_quality_data: List[AirQualityValue]=None, co2_data: List[CO2Value]=None, humidity_data: List[HumidityValue]=None, light_intensity_data: List[LightIntensityValue]=None, sound_data: List[SoundValue]=None, temperature_data: List[TemperatureValue]=None, voc_data: List[VOCValue]=None, room_facilites_data: List[RoomFacilities]=None):  # noqa: E501
        """InlineResponse201Room - a model defined in Swagger

        :param name: The name of this InlineResponse201Room.  # noqa: E501
        :type name: str
        :param air_quality_data: The air_quality_data of this InlineResponse201Room.  # noqa: E501
        :type air_quality_data: List[AirQualityValue]
        :param co2_data: The co2_data of this InlineResponse201Room.  # noqa: E501
        :type co2_data: List[CO2Value]
        :param humidity_data: The humidity_data of this InlineResponse201Room.  # noqa: E501
        :type humidity_data: List[HumidityValue]
        :param light_intensity_data: The light_intensity_data of this InlineResponse201Room.  # noqa: E501
        :type light_intensity_data: List[LightIntensityValue]
        :param sound_data: The sound_data of this InlineResponse201Room.  # noqa: E501
        :type sound_data: List[SoundValue]
        :param temperature_data: The temperature_data of this InlineResponse201Room.  # noqa: E501
        :type temperature_data: List[TemperatureValue]
        :param voc_data: The voc_data of this InlineResponse201Room.  # noqa: E501
        :type voc_data: List[VOCValue]
        :param room_facilites_data: The room_facilites_data of this InlineResponse201Room.  # noqa: E501
        :type room_facilites_data: List[RoomFacilities]
        """
        self.swagger_types = {
            'name': str,
            'air_quality_data': List[AirQualityValue],
            'co2_data': List[CO2Value],
            'humidity_data': List[HumidityValue],
            'light_intensity_data': List[LightIntensityValue],
            'sound_data': List[SoundValue],
            'temperature_data': List[TemperatureValue],
            'voc_data': List[VOCValue],
            'room_facilites_data': List[RoomFacilities]
        }

        self.attribute_map = {
            'name': 'name',
            'air_quality_data': 'Air_Quality_Data',
            'co2_data': 'CO2_Data',
            'humidity_data': 'Humidity_Data',
            'light_intensity_data': 'Light_Intensity_Data',
            'sound_data': 'Sound_Data',
            'temperature_data': 'Temperature_Data',
            'voc_data': 'VOC_Data',
            'room_facilites_data': 'Room_facilites_Data'
        }
        self._name = name
        self._air_quality_data = air_quality_data
        self._co2_data = co2_data
        self._humidity_data = humidity_data
        self._light_intensity_data = light_intensity_data
        self._sound_data = sound_data
        self._temperature_data = temperature_data
        self._voc_data = voc_data
        self._room_facilites_data = room_facilites_data

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse201Room':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_201_room of this InlineResponse201Room.  # noqa: E501
        :rtype: InlineResponse201Room
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this InlineResponse201Room.

        Name of the room  # noqa: E501

        :return: The name of this InlineResponse201Room.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this InlineResponse201Room.

        Name of the room  # noqa: E501

        :param name: The name of this InlineResponse201Room.
        :type name: str
        """

        self._name = name

    @property
    def air_quality_data(self) -> List[AirQualityValue]:
        """Gets the air_quality_data of this InlineResponse201Room.


        :return: The air_quality_data of this InlineResponse201Room.
        :rtype: List[AirQualityValue]
        """
        return self._air_quality_data

    @air_quality_data.setter
    def air_quality_data(self, air_quality_data: List[AirQualityValue]):
        """Sets the air_quality_data of this InlineResponse201Room.


        :param air_quality_data: The air_quality_data of this InlineResponse201Room.
        :type air_quality_data: List[AirQualityValue]
        """

        self._air_quality_data = air_quality_data

    @property
    def co2_data(self) -> List[CO2Value]:
        """Gets the co2_data of this InlineResponse201Room.


        :return: The co2_data of this InlineResponse201Room.
        :rtype: List[CO2Value]
        """
        return self._co2_data

    @co2_data.setter
    def co2_data(self, co2_data: List[CO2Value]):
        """Sets the co2_data of this InlineResponse201Room.


        :param co2_data: The co2_data of this InlineResponse201Room.
        :type co2_data: List[CO2Value]
        """

        self._co2_data = co2_data

    @property
    def humidity_data(self) -> List[HumidityValue]:
        """Gets the humidity_data of this InlineResponse201Room.


        :return: The humidity_data of this InlineResponse201Room.
        :rtype: List[HumidityValue]
        """
        return self._humidity_data

    @humidity_data.setter
    def humidity_data(self, humidity_data: List[HumidityValue]):
        """Sets the humidity_data of this InlineResponse201Room.


        :param humidity_data: The humidity_data of this InlineResponse201Room.
        :type humidity_data: List[HumidityValue]
        """

        self._humidity_data = humidity_data

    @property
    def light_intensity_data(self) -> List[LightIntensityValue]:
        """Gets the light_intensity_data of this InlineResponse201Room.


        :return: The light_intensity_data of this InlineResponse201Room.
        :rtype: List[LightIntensityValue]
        """
        return self._light_intensity_data

    @light_intensity_data.setter
    def light_intensity_data(self, light_intensity_data: List[LightIntensityValue]):
        """Sets the light_intensity_data of this InlineResponse201Room.


        :param light_intensity_data: The light_intensity_data of this InlineResponse201Room.
        :type light_intensity_data: List[LightIntensityValue]
        """

        self._light_intensity_data = light_intensity_data

    @property
    def sound_data(self) -> List[SoundValue]:
        """Gets the sound_data of this InlineResponse201Room.


        :return: The sound_data of this InlineResponse201Room.
        :rtype: List[SoundValue]
        """
        return self._sound_data

    @sound_data.setter
    def sound_data(self, sound_data: List[SoundValue]):
        """Sets the sound_data of this InlineResponse201Room.


        :param sound_data: The sound_data of this InlineResponse201Room.
        :type sound_data: List[SoundValue]
        """

        self._sound_data = sound_data

    @property
    def temperature_data(self) -> List[TemperatureValue]:
        """Gets the temperature_data of this InlineResponse201Room.


        :return: The temperature_data of this InlineResponse201Room.
        :rtype: List[TemperatureValue]
        """
        return self._temperature_data

    @temperature_data.setter
    def temperature_data(self, temperature_data: List[TemperatureValue]):
        """Sets the temperature_data of this InlineResponse201Room.


        :param temperature_data: The temperature_data of this InlineResponse201Room.
        :type temperature_data: List[TemperatureValue]
        """

        self._temperature_data = temperature_data

    @property
    def voc_data(self) -> List[VOCValue]:
        """Gets the voc_data of this InlineResponse201Room.


        :return: The voc_data of this InlineResponse201Room.
        :rtype: List[VOCValue]
        """
        return self._voc_data

    @voc_data.setter
    def voc_data(self, voc_data: List[VOCValue]):
        """Sets the voc_data of this InlineResponse201Room.


        :param voc_data: The voc_data of this InlineResponse201Room.
        :type voc_data: List[VOCValue]
        """

        self._voc_data = voc_data

    @property
    def room_facilites_data(self) -> List[RoomFacilities]:
        """Gets the room_facilites_data of this InlineResponse201Room.


        :return: The room_facilites_data of this InlineResponse201Room.
        :rtype: List[RoomFacilities]
        """
        return self._room_facilites_data

    @room_facilites_data.setter
    def room_facilites_data(self, room_facilites_data: List[RoomFacilities]):
        """Sets the room_facilites_data of this InlineResponse201Room.


        :param room_facilites_data: The room_facilites_data of this InlineResponse201Room.
        :type room_facilites_data: List[RoomFacilities]
        """

        self._room_facilites_data = room_facilites_data
