# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.air_quality_value import AirQualityValue  # noqa: F401,E501
from swagger_server import util


class InlineResponse2002(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, room_name: str=None, air_quality_data: List[AirQualityValue]=None):  # noqa: E501
        """InlineResponse2002 - a model defined in Swagger

        :param room_name: The room_name of this InlineResponse2002.  # noqa: E501
        :type room_name: str
        :param air_quality_data: The air_quality_data of this InlineResponse2002.  # noqa: E501
        :type air_quality_data: List[AirQualityValue]
        """
        self.swagger_types = {
            'room_name': str,
            'air_quality_data': List[AirQualityValue]
        }

        self.attribute_map = {
            'room_name': 'room_name',
            'air_quality_data': 'air_quality_data'
        }
        self._room_name = room_name
        self._air_quality_data = air_quality_data

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2002':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_2 of this InlineResponse2002.  # noqa: E501
        :rtype: InlineResponse2002
        """
        return util.deserialize_model(dikt, cls)

    @property
    def room_name(self) -> str:
        """Gets the room_name of this InlineResponse2002.

        Name of the room  # noqa: E501

        :return: The room_name of this InlineResponse2002.
        :rtype: str
        """
        return self._room_name

    @room_name.setter
    def room_name(self, room_name: str):
        """Sets the room_name of this InlineResponse2002.

        Name of the room  # noqa: E501

        :param room_name: The room_name of this InlineResponse2002.
        :type room_name: str
        """

        self._room_name = room_name

    @property
    def air_quality_data(self) -> List[AirQualityValue]:
        """Gets the air_quality_data of this InlineResponse2002.

        List of air quality values for the room  # noqa: E501

        :return: The air_quality_data of this InlineResponse2002.
        :rtype: List[AirQualityValue]
        """
        return self._air_quality_data

    @air_quality_data.setter
    def air_quality_data(self, air_quality_data: List[AirQualityValue]):
        """Sets the air_quality_data of this InlineResponse2002.

        List of air quality values for the room  # noqa: E501

        :param air_quality_data: The air_quality_data of this InlineResponse2002.
        :type air_quality_data: List[AirQualityValue]
        """

        self._air_quality_data = air_quality_data
