# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from swagger_server import util
from swagger_server.models.base_model_ import Model
from swagger_server.models.humidity_value import HumidityValue  # noqa: F401,E501


class InlineResponse2004(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(
        self, room_name: str = None, humidity_data: List[HumidityValue] = None
    ):  # noqa: E501
        """InlineResponse2004 - a model defined in Swagger

        :param room_name: The room_name of this InlineResponse2004.  # noqa: E501
        :type room_name: str
        :param humidity_data: The humidity_data of this InlineResponse2004.  # noqa: E501
        :type humidity_data: List[HumidityValue]
        """
        self.swagger_types = {"room_name": str, "humidity_data": List[HumidityValue]}

        self.attribute_map = {
            "room_name": "room_name",
            "humidity_data": "humidity_data",
        }
        self._room_name = room_name
        self._humidity_data = humidity_data

    @classmethod
    def from_dict(cls, dikt) -> "InlineResponse2004":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_4 of this InlineResponse2004.  # noqa: E501
        :rtype: InlineResponse2004
        """
        return util.deserialize_model(dikt, cls)

    @property
    def room_name(self) -> str:
        """Gets the room_name of this InlineResponse2004.

        Name of the room  # noqa: E501

        :return: The room_name of this InlineResponse2004.
        :rtype: str
        """
        return self._room_name

    @room_name.setter
    def room_name(self, room_name: str):
        """Sets the room_name of this InlineResponse2004.

        Name of the room  # noqa: E501

        :param room_name: The room_name of this InlineResponse2004.
        :type room_name: str
        """

        self._room_name = room_name

    @property
    def humidity_data(self) -> List[HumidityValue]:
        """Gets the humidity_data of this InlineResponse2004.

        List of humidity level values for the room  # noqa: E501

        :return: The humidity_data of this InlineResponse2004.
        :rtype: List[HumidityValue]
        """
        return self._humidity_data

    @humidity_data.setter
    def humidity_data(self, humidity_data: List[HumidityValue]):
        """Sets the humidity_data of this InlineResponse2004.

        List of humidity level values for the room  # noqa: E501

        :param humidity_data: The humidity_data of this InlineResponse2004.
        :type humidity_data: List[HumidityValue]
        """

        self._humidity_data = humidity_data
