# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from swagger_server import util
from swagger_server.models.base_model_ import Model
<<<<<<< HEAD:src/application/src/api/swagger_server/models/inline_response2007.py
from swagger_server.models.temperature_value import TemperatureValue  # noqa: F401,E501
=======
from swagger_server.models.sound_value import SoundValue  # noqa: F401,E501
from swagger_server import util
>>>>>>> API_Database:src/application/src/swagger_server/models/inline_response2007.py


class InlineResponse2007(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
<<<<<<< HEAD:src/application/src/api/swagger_server/models/inline_response2007.py

    def __init__(
        self, room_name: str = None, temperature_data: List[TemperatureValue] = None
    ):  # noqa: E501
=======
    def __init__(self, room_name: str=None, sound_data: List[SoundValue]=None):  # noqa: E501
>>>>>>> API_Database:src/application/src/swagger_server/models/inline_response2007.py
        """InlineResponse2007 - a model defined in Swagger

        :param room_name: The room_name of this InlineResponse2007.  # noqa: E501
        :type room_name: str
        :param sound_data: The sound_data of this InlineResponse2007.  # noqa: E501
        :type sound_data: List[SoundValue]
        """
        self.swagger_types = {
<<<<<<< HEAD:src/application/src/api/swagger_server/models/inline_response2007.py
            "room_name": str,
            "temperature_data": List[TemperatureValue],
        }

        self.attribute_map = {
            "room_name": "room_name",
            "temperature_data": "temperature_data",
=======
            'room_name': str,
            'sound_data': List[SoundValue]
        }

        self.attribute_map = {
            'room_name': 'room_name',
            'sound_data': 'sound_data'
>>>>>>> API_Database:src/application/src/swagger_server/models/inline_response2007.py
        }
        self._room_name = room_name
        self._sound_data = sound_data

    @classmethod
    def from_dict(cls, dikt) -> "InlineResponse2007":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_7 of this InlineResponse2007.  # noqa: E501
        :rtype: InlineResponse2007
        """
        return util.deserialize_model(dikt, cls)

    @property
    def room_name(self) -> str:
        """Gets the room_name of this InlineResponse2007.

        Name of the room  # noqa: E501

        :return: The room_name of this InlineResponse2007.
        :rtype: str
        """
        return self._room_name

    @room_name.setter
    def room_name(self, room_name: str):
        """Sets the room_name of this InlineResponse2007.

        Name of the room  # noqa: E501

        :param room_name: The room_name of this InlineResponse2007.
        :type room_name: str
        """

        self._room_name = room_name

    @property
    def sound_data(self) -> List[SoundValue]:
        """Gets the sound_data of this InlineResponse2007.

        List of sound level values for the room  # noqa: E501

        :return: The sound_data of this InlineResponse2007.
        :rtype: List[SoundValue]
        """
        return self._sound_data

    @sound_data.setter
    def sound_data(self, sound_data: List[SoundValue]):
        """Sets the sound_data of this InlineResponse2007.

        List of sound level values for the room  # noqa: E501

        :param sound_data: The sound_data of this InlineResponse2007.
        :type sound_data: List[SoundValue]
        """

        self._sound_data = sound_data
