# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from swagger_server import util
from swagger_server.models.base_model_ import Model
from swagger_server.models.temperature_value import TemperatureValue  # noqa: F401,E501


class InlineResponse2007(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(
        self, room_name: str = None, temperature_data: List[TemperatureValue] = None
    ):  # noqa: E501
        """InlineResponse2007 - a model defined in Swagger

        :param room_name: The room_name of this InlineResponse2007.  # noqa: E501
        :type room_name: str
        :param temperature_data: The temperature_data of this InlineResponse2007.  # noqa: E501
        :type temperature_data: List[TemperatureValue]
        """
        self.swagger_types = {
            "room_name": str,
            "temperature_data": List[TemperatureValue],
        }

        self.attribute_map = {
            "room_name": "room_name",
            "temperature_data": "temperature_data",
        }
        self._room_name = room_name
        self._temperature_data = temperature_data

    @classmethod
    def from_dict(cls, dikt) -> "InlineResponse2007":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_7 of this InlineResponse2007.  # noqa: E501
        :rtype: InlineResponse2007
        """
        return util.deserialize_model(dikt, cls)

    @property
    def room_name(self) -> str:
        """Gets the room_name of this InlineResponse2007.

        Name of the room  # noqa: E501

        :return: The room_name of this InlineResponse2007.
        :rtype: str
        """
        return self._room_name

    @room_name.setter
    def room_name(self, room_name: str):
        """Sets the room_name of this InlineResponse2007.

        Name of the room  # noqa: E501

        :param room_name: The room_name of this InlineResponse2007.
        :type room_name: str
        """

        self._room_name = room_name

    @property
    def temperature_data(self) -> List[TemperatureValue]:
        """Gets the temperature_data of this InlineResponse2007.

        List of temperature values for the room  # noqa: E501

        :return: The temperature_data of this InlineResponse2007.
        :rtype: List[TemperatureValue]
        """
        return self._temperature_data

    @temperature_data.setter
    def temperature_data(self, temperature_data: List[TemperatureValue]):
        """Sets the temperature_data of this InlineResponse2007.

        List of temperature values for the room  # noqa: E501

        :param temperature_data: The temperature_data of this InlineResponse2007.
        :type temperature_data: List[TemperatureValue]
        """

        self._temperature_data = temperature_data
