# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from swagger_server import util
from swagger_server.models.base_model_ import Model


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, old_name: str = None, updated_name: str = None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param old_name: The old_name of this InlineResponse2001.  # noqa: E501
        :type old_name: str
        :param updated_name: The updated_name of this InlineResponse2001.  # noqa: E501
        :type updated_name: str
        """
        self.swagger_types = {"old_name": str, "updated_name": str}

        self.attribute_map = {"old_name": "old_name", "updated_name": "updated_name"}
        self._old_name = old_name
        self._updated_name = updated_name

    @classmethod
    def from_dict(cls, dikt) -> "InlineResponse2001":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def old_name(self) -> str:
        """Gets the old_name of this InlineResponse2001.


        :return: The old_name of this InlineResponse2001.
        :rtype: str
        """
        return self._old_name

    @old_name.setter
    def old_name(self, old_name: str):
        """Sets the old_name of this InlineResponse2001.


        :param old_name: The old_name of this InlineResponse2001.
        :type old_name: str
        """

        self._old_name = old_name

    @property
    def updated_name(self) -> str:
        """Gets the updated_name of this InlineResponse2001.


        :return: The updated_name of this InlineResponse2001.
        :rtype: str
        """
        return self._updated_name

    @updated_name.setter
    def updated_name(self, updated_name: str):
        """Sets the updated_name of this InlineResponse2001.


        :param updated_name: The updated_name of this InlineResponse2001.
        :type updated_name: str
        """

        self._updated_name = updated_name
