# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.room_facilities import RoomFacilities  # noqa: F401,E501
from swagger_server import util


class InlineResponse20010(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, room_name: str = None, room_facilities: RoomFacilities = None):  # noqa: E501
        """InlineResponse20010 - a model defined in Swagger

        :param room_name: The room_name of this InlineResponse20010.  # noqa: E501
        :type room_name: str
        :param room_facilities: The room_facilities of this InlineResponse20010.  # noqa: E501
        :type room_facilities: RoomFacilities
        """
        self.swagger_types = {"room_name": str, "room_facilities": RoomFacilities}

        self.attribute_map = {
            "room_name": "room_name",
            "room_facilities": "room_facilities",
        }
        self._room_name = room_name
        self._room_facilities = room_facilities

    @classmethod
    def from_dict(cls, dikt) -> "InlineResponse20010":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_10 of this InlineResponse20010.  # noqa: E501
        :rtype: InlineResponse20010
        """
        return util.deserialize_model(dikt, cls)

    @property
    def room_name(self) -> str:
        """Gets the room_name of this InlineResponse20010.

        Name of the room  # noqa: E501

        :return: The room_name of this InlineResponse20010.
        :rtype: str
        """
        return self._room_name

    @room_name.setter
    def room_name(self, room_name: str):
        """Sets the room_name of this InlineResponse20010.

        Name of the room  # noqa: E501

        :param room_name: The room_name of this InlineResponse20010.
        :type room_name: str
        """

        self._room_name = room_name

    @property
    def room_facilities(self) -> RoomFacilities:
        """Gets the room_facilities of this InlineResponse20010.


        :return: The room_facilities of this InlineResponse20010.
        :rtype: RoomFacilities
        """
        return self._room_facilities

    @room_facilities.setter
    def room_facilities(self, room_facilities: RoomFacilities):
        """Sets the room_facilities of this InlineResponse20010.


        :param room_facilities: The room_facilities of this InlineResponse20010.
        :type room_facilities: RoomFacilities
        """

        self._room_facilities = room_facilities
