# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from swagger_server import util
from swagger_server.models.base_model_ import Model


class RoomFacilities(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(
        self,
        videoprojector: bool = None,
        seating_capacity: int = None,
        computers: int = None,
        robots_for_training: int = None,
    ):  # noqa: E501
        """RoomFacilities - a model defined in Swagger

        :param videoprojector: The videoprojector of this RoomFacilities.  # noqa: E501
        :type videoprojector: bool
        :param seating_capacity: The seating_capacity of this RoomFacilities.  # noqa: E501
        :type seating_capacity: int
        :param computers: The computers of this RoomFacilities.  # noqa: E501
        :type computers: int
        :param robots_for_training: The robots_for_training of this RoomFacilities.  # noqa: E501
        :type robots_for_training: int
        """
        self.swagger_types = {
            "videoprojector": bool,
            "seating_capacity": int,
            "computers": int,
            "robots_for_training": int,
        }

        self.attribute_map = {
            "videoprojector": "videoprojector",
            "seating_capacity": "seating_capacity",
            "computers": "computers",
            "robots_for_training": "robots_for_training",
        }
        self._videoprojector = videoprojector
        self._seating_capacity = seating_capacity
        self._computers = computers
        self._robots_for_training = robots_for_training

    @classmethod
    def from_dict(cls, dikt) -> "RoomFacilities":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RoomFacilities of this RoomFacilities.  # noqa: E501
        :rtype: RoomFacilities
        """
        return util.deserialize_model(dikt, cls)

    @property
    def videoprojector(self) -> bool:
        """Gets the videoprojector of this RoomFacilities.

        Indicates whether the room has a videoprojector  # noqa: E501

        :return: The videoprojector of this RoomFacilities.
        :rtype: bool
        """
        return self._videoprojector

    @videoprojector.setter
    def videoprojector(self, videoprojector: bool):
        """Sets the videoprojector of this RoomFacilities.

        Indicates whether the room has a videoprojector  # noqa: E501

        :param videoprojector: The videoprojector of this RoomFacilities.
        :type videoprojector: bool
        """

        self._videoprojector = videoprojector

    @property
    def seating_capacity(self) -> int:
        """Gets the seating_capacity of this RoomFacilities.

        Seating capacity of the room  # noqa: E501

        :return: The seating_capacity of this RoomFacilities.
        :rtype: int
        """
        return self._seating_capacity

    @seating_capacity.setter
    def seating_capacity(self, seating_capacity: int):
        """Sets the seating_capacity of this RoomFacilities.

        Seating capacity of the room  # noqa: E501

        :param seating_capacity: The seating_capacity of this RoomFacilities.
        :type seating_capacity: int
        """

        self._seating_capacity = seating_capacity

    @property
    def computers(self) -> int:
        """Gets the computers of this RoomFacilities.

        Number of computers available in the room  # noqa: E501

        :return: The computers of this RoomFacilities.
        :rtype: int
        """
        return self._computers

    @computers.setter
    def computers(self, computers: int):
        """Sets the computers of this RoomFacilities.

        Number of computers available in the room  # noqa: E501

        :param computers: The computers of this RoomFacilities.
        :type computers: int
        """

        self._computers = computers

    @property
    def robots_for_training(self) -> int:
        """Gets the robots_for_training of this RoomFacilities.

        Number of robots available for training in the room  # noqa: E501

        :return: The robots_for_training of this RoomFacilities.
        :rtype: int
        """
        return self._robots_for_training

    @robots_for_training.setter
    def robots_for_training(self, robots_for_training: int):
        """Sets the robots_for_training of this RoomFacilities.

        Number of robots available for training in the room  # noqa: E501

        :param robots_for_training: The robots_for_training of this RoomFacilities.
        :type robots_for_training: int
        """

        self._robots_for_training = robots_for_training
