# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.sound_value import SoundValue  # noqa: F401,E501
from swagger_server import util


class SoundRoom(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, sound_values: List[SoundValue]=None):  # noqa: E501
        """SoundRoom - a model defined in Swagger

        :param name: The name of this SoundRoom.  # noqa: E501
        :type name: str
        :param sound_values: The sound_values of this SoundRoom.  # noqa: E501
        :type sound_values: List[SoundValue]
        """
        self.swagger_types = {
            'name': str,
            'sound_values': List[SoundValue]
        }

        self.attribute_map = {
            'name': 'name',
            'sound_values': 'sound_values'
        }
        self._name = name
        self._sound_values = sound_values

    @classmethod
    def from_dict(cls, dikt) -> 'SoundRoom':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SoundRoom of this SoundRoom.  # noqa: E501
        :rtype: SoundRoom
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this SoundRoom.

        Name of the room  # noqa: E501

        :return: The name of this SoundRoom.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this SoundRoom.

        Name of the room  # noqa: E501

        :param name: The name of this SoundRoom.
        :type name: str
        """

        self._name = name

    @property
    def sound_values(self) -> List[SoundValue]:
        """Gets the sound_values of this SoundRoom.

        Sound level readings for a specific room  # noqa: E501

        :return: The sound_values of this SoundRoom.
        :rtype: List[SoundValue]
        """
        return self._sound_values

    @sound_values.setter
    def sound_values(self, sound_values: List[SoundValue]):
        """Sets the sound_values of this SoundRoom.

        Sound level readings for a specific room  # noqa: E501

        :param sound_values: The sound_values of this SoundRoom.
        :type sound_values: List[SoundValue]
        """

        self._sound_values = sound_values
