# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from swagger_server import util
from swagger_server.models.base_model_ import Model
from swagger_server.models.temperature_value import TemperatureValue  # noqa: F401,E501


class TemperatureRoom(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(
        self, name: str = None, temperature_values: List[TemperatureValue] = None
    ):  # noqa: E501
        """TemperatureRoom - a model defined in Swagger

        :param name: The name of this TemperatureRoom.  # noqa: E501
        :type name: str
        :param temperature_values: The temperature_values of this TemperatureRoom.  # noqa: E501
        :type temperature_values: List[TemperatureValue]
        """
        self.swagger_types = {"name": str, "temperature_values": List[TemperatureValue]}

        self.attribute_map = {
            "name": "name",
            "temperature_values": "temperature_values",
        }
        self._name = name
        self._temperature_values = temperature_values

    @classmethod
    def from_dict(cls, dikt) -> "TemperatureRoom":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TemperatureRoom of this TemperatureRoom.  # noqa: E501
        :rtype: TemperatureRoom
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this TemperatureRoom.

        Name of the room  # noqa: E501

        :return: The name of this TemperatureRoom.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this TemperatureRoom.

        Name of the room  # noqa: E501

        :param name: The name of this TemperatureRoom.
        :type name: str
        """

        self._name = name

    @property
    def temperature_values(self) -> List[TemperatureValue]:
        """Gets the temperature_values of this TemperatureRoom.

        Temperature readings for a specific room  # noqa: E501

        :return: The temperature_values of this TemperatureRoom.
        :rtype: List[TemperatureValue]
        """
        return self._temperature_values

    @temperature_values.setter
    def temperature_values(self, temperature_values: List[TemperatureValue]):
        """Sets the temperature_values of this TemperatureRoom.

        Temperature readings for a specific room  # noqa: E501

        :param temperature_values: The temperature_values of this TemperatureRoom.
        :type temperature_values: List[TemperatureValue]
        """

        self._temperature_values = temperature_values
