# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from swagger_server import util
from swagger_server.models.base_model_ import Model


class TemperatureValue(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, timestamp: datetime = None, temperature: float = None):  # noqa: E501
        """TemperatureValue - a model defined in Swagger

        :param timestamp: The timestamp of this TemperatureValue.  # noqa: E501
        :type timestamp: datetime
        :param temperature: The temperature of this TemperatureValue.  # noqa: E501
        :type temperature: float
        """
        self.swagger_types = {"timestamp": datetime, "temperature": float}

        self.attribute_map = {"timestamp": "timestamp", "temperature": "temperature"}
        self._timestamp = timestamp
        self._temperature = temperature

    @classmethod
    def from_dict(cls, dikt) -> "TemperatureValue":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TemperatureValue of this TemperatureValue.  # noqa: E501
        :rtype: TemperatureValue
        """
        return util.deserialize_model(dikt, cls)

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this TemperatureValue.

        Timestamp of the temperature reading  # noqa: E501

        :return: The timestamp of this TemperatureValue.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this TemperatureValue.

        Timestamp of the temperature reading  # noqa: E501

        :param timestamp: The timestamp of this TemperatureValue.
        :type timestamp: datetime
        """

        self._timestamp = timestamp

    @property
    def temperature(self) -> float:
        """Gets the temperature of this TemperatureValue.

        Temperature in degrees Celsius  # noqa: E501

        :return: The temperature of this TemperatureValue.
        :rtype: float
        """
        return self._temperature

    @temperature.setter
    def temperature(self, temperature: float):
        """Sets the temperature of this TemperatureValue.

        Temperature in degrees Celsius  # noqa: E501

        :param temperature: The temperature of this TemperatureValue.
        :type temperature: float
        """

        self._temperature = temperature
