# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from swagger_server import util
from swagger_server.models.base_model_ import Model


class VOCValue(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, timestamp: datetime = None, voc_level: float = None):  # noqa: E501
        """VOCValue - a model defined in Swagger

        :param timestamp: The timestamp of this VOCValue.  # noqa: E501
        :type timestamp: datetime
        :param voc_level: The voc_level of this VOCValue.  # noqa: E501
        :type voc_level: float
        """
        self.swagger_types = {"timestamp": datetime, "voc_level": float}

        self.attribute_map = {"timestamp": "timestamp", "voc_level": "VOC_level"}
        self._timestamp = timestamp
        self._voc_level = voc_level

    @classmethod
    def from_dict(cls, dikt) -> "VOCValue":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VOCValue of this VOCValue.  # noqa: E501
        :rtype: VOCValue
        """
        return util.deserialize_model(dikt, cls)

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this VOCValue.

        Timestamp of the VOC level reading  # noqa: E501

        :return: The timestamp of this VOCValue.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this VOCValue.

        Timestamp of the VOC level reading  # noqa: E501

        :param timestamp: The timestamp of this VOCValue.
        :type timestamp: datetime
        """

        self._timestamp = timestamp

    @property
    def voc_level(self) -> float:
        """Gets the voc_level of this VOCValue.

        VOC concentration in the air  # noqa: E501

        :return: The voc_level of this VOCValue.
        :rtype: float
        """
        return self._voc_level

    @voc_level.setter
    def voc_level(self, voc_level: float):
        """Sets the voc_level of this VOCValue.

        VOC concentration in the air  # noqa: E501

        :param voc_level: The voc_level of this VOCValue.
        :type voc_level: float
        """

        self._voc_level = voc_level
